sudo: required
services:
  - docker

before_install:
  - docker build -t nvracar/my-app-2-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nvracar/my-app-2-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t nvracar/mu-app-2-client ./client
  - docker build -t nvracar/mu-app-2-nginx ./nginx
  - docker build -t nvracar/mu-app-2-server ./server
  - docker build -t nvracar/mu-app-2-worker ./worker

  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push nvracar/mu-app-2-client
  - docker push nvracar/mu-app-2-nginx
  - docker push nvracar/mu-app-2-server
  - docker push nvracar/mu-app-2-worker
